---
destination : /tmp/md-cache
auto        : false
lsi         : false
pygments    : true
permalink   : none
markdown    : maruku
exclude     : client,gwt-unitCache,server,shared,scripts,war,.idea,build.xml,lib,blog.iml,md-cache,logs,progess

maruku:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

    
